import type { Card } from '../types';

export const challenges: Card[] = [
  {
    id: 'chal-platform-selfie',
    kind: 'challenge',
    title: 'Platform Selfie',
    description: 'Take a selfie on the platform showing the station name board.',
    reward: 20,
    penalty: 5,
    timerSeconds: 5 * 60,
    resolution: 'photo',
  },
  {
    id: 'chal-name-the-line',
    kind: 'challenge',
    title: 'Name the Line',
    description:
      'Without checking the app, name every line that serves this station. Self-report honestly.',
    reward: 15,
    penalty: 5,
    timerSeconds: 90,
    resolution: 'self-report',
  },
  {
    id: 'chal-touch-all-platforms',
    kind: 'challenge',
    title: 'Tour de Platforms',
    description: 'Walk to and stand on every platform at this station before continuing.',
    reward: 25,
    penalty: 10,
    timerSeconds: 10 * 60,
    resolution: 'self-report',
  },
  {
    id: 'chal-board-within-2',
    kind: 'challenge',
    title: 'Quick Boarding',
    description: 'Board a train at this station within the next 2 minutes.',
    reward: 30,
    penalty: 10,
    timerSeconds: 2 * 60,
    resolution: 'station-arrival',
  },
  {
    id: 'chal-three-line-dadar',
    kind: 'challenge',
    title: 'Three Line Dadar',
    description: 'Visit a platform of all three lines that serve Dadar (WR, CR, Metro 3).',
    reward: 50,
    penalty: 0,
    timerSeconds: 30 * 60,
    resolution: 'self-report',
    zones: ['central-mumbai'],
  },
  {
    id: 'chal-bandra-skywalk',
    kind: 'challenge',
    title: 'Bandra Skywalk',
    description: 'Use the Bandra skywalk to exit the station and take a photo at its end.',
    reward: 25,
    penalty: 5,
    timerSeconds: 15 * 60,
    resolution: 'photo',
    zones: ['western-suburbs'],
  },
  {
    id: 'chal-trivia-station-year',
    kind: 'challenge',
    title: 'Station Trivia',
    description: 'Ask a station staff member or look up: what year did this station first open?',
    reward: 15,
    penalty: 5,
    timerSeconds: 5 * 60,
    resolution: 'self-report',
  },
  {
    id: 'chal-csmt-heritage',
    kind: 'challenge',
    title: 'CSMT Heritage',
    description: 'Find and photograph the heritage clock tower at CSMT.',
    reward: 30,
    penalty: 5,
    timerSeconds: 15 * 60,
    resolution: 'photo',
    zones: ['south-mumbai'],
  },
  {
    id: 'chal-andheri-flyover',
    kind: 'challenge',
    title: 'Andheri Crossing',
    description: 'Cross from the East to the West side of Andheri (or vice versa) via the FOB.',
    reward: 20,
    penalty: 5,
    timerSeconds: 10 * 60,
    resolution: 'self-report',
    zones: ['western-suburbs'],
  },
  {
    id: 'chal-tap-afc-gate',
    kind: 'challenge',
    title: 'Tap In',
    description: 'Tap your card or QR at the AFC gate of any Metro station and capture the screen.',
    reward: 20,
    penalty: 5,
    timerSeconds: 10 * 60,
    resolution: 'photo',
  },
];
