import type { Card } from '../types';

export const curses: Card[] = [
  {
    id: 'curse-slow-local',
    kind: 'curse',
    title: 'Slow Local Only',
    description: 'For the next 30 minutes you may not board any Fast train. Slow locals only.',
    reward: 0,
    penalty: 25,
    timerSeconds: 30 * 60,
    resolution: 'timer',
  },
  {
    id: 'curse-wrong-way',
    kind: 'curse',
    title: 'Wrong Way',
    description:
      'The next station you reach must be in the opposite direction of your last move on this line.',
    reward: 0,
    penalty: 20,
    timerSeconds: 0,
    resolution: 'station-arrival',
  },
  {
    id: 'curse-line-lock-harbour',
    kind: 'curse',
    title: 'Line Lock: Harbour',
    description: 'For the next 20 minutes you may only travel on the Harbour Line.',
    reward: 0,
    penalty: 30,
    timerSeconds: 20 * 60,
    resolution: 'timer',
  },
  {
    id: 'curse-no-csmt',
    kind: 'curse',
    title: 'No CSMT',
    description: 'CSMT is closed to you for the next hour. You cannot board, alight, or pass through.',
    reward: 0,
    penalty: 40,
    timerSeconds: 60 * 60,
    resolution: 'timer',
  },
  {
    id: 'curse-metro-detour',
    kind: 'curse',
    title: 'Metro Detour',
    description: 'You must travel at least one segment on Metro within the next 45 minutes.',
    reward: 15,
    penalty: 25,
    timerSeconds: 45 * 60,
    resolution: 'station-arrival',
  },
  {
    id: 'curse-foot-over-bridge',
    kind: 'curse',
    title: 'Foot Over Bridge',
    description:
      'At the next station, exit and re-enter via a different platform before continuing your journey.',
    reward: 10,
    penalty: 15,
    timerSeconds: 0,
    resolution: 'self-report',
  },
  {
    id: 'curse-skip-two',
    kind: 'curse',
    title: 'Skip Two',
    description: 'You must skip the next two stations without alighting.',
    reward: 10,
    penalty: 15,
    timerSeconds: 0,
    resolution: 'station-arrival',
  },
  {
    id: 'curse-platform-ticket',
    kind: 'curse',
    title: 'Platform Ticket',
    description:
      'At the next station, buy a platform ticket and stay on the platform for the duration of one full train arrival before continuing.',
    reward: 10,
    penalty: 10,
    timerSeconds: 0,
    resolution: 'self-report',
  },
  {
    id: 'curse-vada-pav-tax',
    kind: 'curse',
    title: 'Vada Pav Tax',
    description: 'You may not leave the next station you reach until you have eaten a vada pav nearby.',
    reward: 10,
    penalty: 10,
    timerSeconds: 0,
    resolution: 'photo',
  },
  {
    id: 'curse-ladies-side',
    kind: 'curse',
    title: 'Ladies First',
    description:
      'For your next 2 stations of travel you must board on the side closer to the ladies compartment (do not enter the ladies compartment).',
    reward: 10,
    penalty: 15,
    timerSeconds: 0,
    resolution: 'self-report',
  },
];
